/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthCreateRouteImport } from './routes/_auth/create'
import { Route as AuthViewPromptIdRouteImport } from './routes/_auth/view.$promptId'
import { Route as AuthEditPromptIdRouteImport } from './routes/_auth/edit.$promptId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthCreateRoute = AuthCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthViewPromptIdRoute = AuthViewPromptIdRouteImport.update({
  id: '/view/$promptId',
  path: '/view/$promptId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEditPromptIdRoute = AuthEditPromptIdRouteImport.update({
  id: '/edit/$promptId',
  path: '/edit/$promptId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/about': typeof AboutRoute
  '/create': typeof AuthCreateRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/edit/$promptId': typeof AuthEditPromptIdRoute
  '/view/$promptId': typeof AuthViewPromptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/about': typeof AboutRoute
  '/create': typeof AuthCreateRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/edit/$promptId': typeof AuthEditPromptIdRoute
  '/view/$promptId': typeof AuthViewPromptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/create': typeof AuthCreateRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/edit/$promptId': typeof AuthEditPromptIdRoute
  '/_auth/view/$promptId': typeof AuthViewPromptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/register'
    | '/edit/$promptId'
    | '/view/$promptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/login'
    | '/register'
    | '/edit/$promptId'
    | '/view/$promptId'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/about'
    | '/_auth/create'
    | '/_guest/login'
    | '/_guest/register'
    | '/_auth/'
    | '/_auth/edit/$promptId'
    | '/_auth/view/$promptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/create': {
      id: '/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/view/$promptId': {
      id: '/_auth/view/$promptId'
      path: '/view/$promptId'
      fullPath: '/view/$promptId'
      preLoaderRoute: typeof AuthViewPromptIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/edit/$promptId': {
      id: '/_auth/edit/$promptId'
      path: '/edit/$promptId'
      fullPath: '/edit/$promptId'
      preLoaderRoute: typeof AuthEditPromptIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCreateRoute: typeof AuthCreateRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthEditPromptIdRoute: typeof AuthEditPromptIdRoute
  AuthViewPromptIdRoute: typeof AuthViewPromptIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateRoute: AuthCreateRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthEditPromptIdRoute: AuthEditPromptIdRoute,
  AuthViewPromptIdRoute: AuthViewPromptIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
